MetaMask/snap-simple-keyring

packages/snap/package.json, yarn.lock
Use versioned release of `keyring-api`.
=> chore: update `keyring-api` and remove allowed script

package.json, packages/site/package.json, packages/snap/package.json, packages/snap/snap.manifest.json
It's required, otherwise the GitHub action will fail.
=> chore: revert versions to `0.0.0` before release

packages/site/src/App.tsx, packages/site/src/pages/index.tsx
Changes:
- moves client initialization into useEffect after a window check.
=> fix: Move client creation into use effect

packages/site/.env.production, packages/site/.env.production.dist, packages/site/src/config/snap.ts
Previously, to test locally, we had to change the defaultSnapOrigin to `local:http://localhost:8080/`
This is because we misinterpreted the configuration options in template-snap-monorepo.  What they intended was 
```
export const defaultSnapOrigin =
process.env.SNAP_ORIGIN ?? `local:http://localhost:8080`;
```
and then store `SNAP_ORIGIN` in `.env.production` for the npm version
- Run `yarn start`, and the when you install the snap, it should come from http://localhost:8080
- Run `yarn build`, and then in `packages/site` run `yarn dlx serve -s public`
When you install the snap, it should come from `npm:@metamask/snap-simple-keyring-snap`
=> fix: now you don't have to change your defaultSnapOrigin

packages/snap/package.json
As repported internally, we shouldn't ship the `index.ts` file. Instead, the main file should be `dist/bundle.js` ([see examples](https://github.com/MetaMask/snaps/tree/main/packages/examples/packages)).
=> build: update main file (`src/index.ts` -> `dist/bundle.js`)

packages/site/src/components/Header.tsx, packages/site/src/utils/snap.ts
The dApp specifies the Snap version to install by `version` in `packages/site/package.json`
- If the Snap is not installed, Header gives the version to install
- If the Snap is installed, Header gives the version installed
- Informs you if it will install from localhost
- manually change the `version` in `package.json`
- `yarn start` will test in localhost mode
- to test in NPM mode, run `yarn build && yarn dlx serve -s public` then visit http://localhost:3000
=> feat: the dApp specifies the Snap version to install

packages/site/src/pages/index.tsx
This PR adds a check to see if the snap is installed & connected before trying to get the snap's state, otherwise MetaMask will throw the following error:
```text
MetaMask - RPC Error: Unauthorized to perform action. Try requesting the required permission(s) first.
...
{
"code": 4100,
"message": "Unauthorized to perform action. Try requesting the required permission(s) first. ...",
"data": {
"origin": "http://localhost:8000",
"method": "wallet_snap"
}
}
```
=> fix: check if the snap is installed before trying to get its state

packages/site/src/pages/index.tsx
The PR removes the `0x` prefix of the private in the placeholder of the "Import Account" method.
**Before:**
**After:**
=> ui: fix the private key format in the import account placeholder

packages/snap/snap.manifest.json, packages/snap/src/keyring.ts
fixes https://github.com/MetaMask/accounts-planning/issues/57
=> fix: remove private key from options after generating key pair

packages/site/src/pages/index.tsx
Fixes the issue where existing accounts were not being loaded by adding `state.installSnap` to the dependency array.
=> fix: add state.installSnap into dep array

packages/snap/snap.manifest.json, packages/snap/src/keyring.ts
- resolves https://github.com/MetaMask/accounts-planning/issues/72
https://github.com/MetaMask/snap-simple-keyring/assets/22918444/ef11c7a0-836e-4d6a-8e04-393019bebfe8
- Clicking create account on the snap resulted in the account being created despite the response of the users approval flow
- if a user denies the account creation then the snap and the extension would be out of sync
- Clicking remove account on the snap removed the account from the snap and then asked for permission in the extension
- if the user denies the account removal then the snap and the extension would be out of sync
- we ask for permission from the extension first, if it gets accepted then we remove/create the account, if not we throw the `user denied account removal`/`user denied account removal` error …
=> [Fix] Snap and extension are out of sync

packages/snap/package.json, packages/snap/snap.config.ts, packages/snap/snap.manifest.json, packages/snap/src/keyring.ts, packages/snap/tsconfig.json
Set env variables to point to the dapp origin. the dapp origin is either `http://localhost:8000/` when the NODE_ENV is in development or `https://metamask.github.io/snap-simple-keyring/{version}/` in prod
This change follows the environment variable pattern set by the [snap cli](https://github.com/MetaMask/snaps/tree/main/packages/snaps-cli#environment)
This PR works alongside https://github.com/MetaMask/metamask-extension/pull/21312
https://github.com/MetaMask/snap-simple-keyring/assets/22918444/249358c1-ce15-45e8-9284-ec808d3783fd
=> feat: add URL to async approval redirect

packages/snap/snap.manifest.json, packages/snap/src/index.ts, packages/snap/src/keyring.ts, packages/snap/src/stateManagement.ts
This is a security concern raised internally. Although it's an example Snap, we must make sure to adhere to the [security guidelines](https://github.com/MetaMask/keyring-api/blob/main/docs/security.md).
=> fix: remove logs from Snap

packages/site/src/components/Header.tsx
This pr changes how the dapp is fetching the current snap version. Previosly it was done by looking at the site's package json, now it will use the snap's package.json file.
=> fix: use the Snap `package.json` for the update check

packages/site/src/utils/snap.ts
Change the `connectSnap` function to use snapPackageInfo as default instead of packageInfo
=> fix: change `packageInfo` to `snapPackageInfo`

packages/snap/snap.manifest.json, packages/snap/src/keyring.ts, packages/snap/src/util.ts
This PR makes our Snap follow this [guideline](https://github.com/MetaMask/keyring-api/blob/main/docs/security.md#sanitize-errors-to-remove-sensitive-information).
=> fix: sanitize error message when importing invalid private key

packages/site/src/components/Buttons.tsx
This PR moves the "Delete" button into the account details and fixes the right margin.
**Before:**
**After:**
=> ui: move "Delete" button into account details

packages/site/package.json
This is a workaround for <https://github.com/gatsbyjs/gatsby/issues/38483> and should be reverted once it's fixed by Gatsby.
=> build: remove cache before building site

packages/snap/snap.manifest.json, packages/snap/src/index.ts, packages/snap/src/logger.ts, packages/snap/src/stateManagement.ts
This PR adds a logging utility class. It should be used instead of `console.log`.
1. Go to your browser's console
2. Enable all logging levels
3. Start the Snap with `yarn start`
4. Go to the companion dapp
5. Execute a request
6. Verify that the request payload is logged to the console
7. Stop the Snap
8. Edit the Snap's `package.json` file:
```diff
-"start": "NODE_ENV='development' mm-snap watch"
+"start": "NODE_ENV='production' mm-snap watch"
```
3. Start the Snap with `yarn start`
4. Go to the companion dapp
5. Execute a request
6. Verify that the request payload is **not** logged to the console
=> feat: add logger utility

packages/snap/package.json, packages/snap/snap.manifest.json, yarn.lock
A regression was introduced on eth-sig-util 6.0.1 and 7.0.0, see: <https://github.com/MetaMask/eth-sig-util/issues/340>.
This PR bumps this dependency to 7.0.1 which contains the fix.
1. Go to <https://metamask.github.io/test-dapp/>
2. Connect to an account managed by the SSK
3. Go to **Sign Typed Data V4** and click on **Sign**
4. Click on **Verify**
5. The signature should be sucessfully verified
=> fix: update eth-sig-util to fix a regression

package.json, scripts/build-preinstalled-snap.js
- this is the same script that is currently used in the notifications snaps and the watch only account snap: https://github.com/MetaMask/message-signing-snap/blob/main/scripts/build-preinstalled-snap.js
- run `yarn run build-preinstalled-snap`
there should be a local bundle file created.
=> feat: pre installed snap script

package.json, packages/snap/package.json, packages/snap/snap.manifest.json
by building the preinstalled snap in the same step we build the snap, we ensure that we generate the latest `preinstalled-snap.json` and that it will be included in the release.
- yarn build
- there should be the following 3 files in your snap/dist folder....
- `packages/snap/dist/bundle.js`
- `packages/snap/dist/bundle.js.map`
- `packages/snap/dist/preinstalled-snap.json`
=> patch: Include yarn build-preinstalled-snap in main build steps

packages/snap/package.json, packages/snap/scripts/build-preinstalled-snap.js, packages/snap/snap.manifest.json
This change moves the script to build the preinstalled snap inside the snaps package in order for paths to be correctly resolved when building the snap from [npm location](https://www.npmjs.com/package/@metamask/snap-simple-keyring-snap?activeTab=readme)
=> fix: moved build-preinstalled-snap.js script inside snap package

packages/snap/snap.manifest.json, packages/snap/src/permissions.ts
This is needed to enable testing on mobile.
eventually mobile will use the [origin instead of hostname](https://github.com/MetaMask/metamask-mobile/issues/11029)
=> fix: Allow the metamask.github.io to call the snap

packages/snap/snap.manifest.json
Adds `"metamask.github.io"` to the [list of allowedOrigins](https://github.com/MetaMask/snap-simple-keyring/blob/main/packages/snap/snap.manifest.json#L22) for the `endowment:keyring` in order to overcome blocker with SnapsController rejecting requests from the domain without the "https://" prefix
=> feat: add "metamask.github.io" to `allowedOrigins` in the `endowment:keyring`

packages/site/package.json, packages/snap/package.json, packages/snap/snap.manifest.json, yarn.lock
Aligning the `keyring-api` version to use the new packages from the monorepo.
Also updated the version for the dapp.
=> chore: bump keyring-api to ^8.1.3

packages/site/package.json, packages/snap/package.json, packages/snap/snap.manifest.json, packages/snap/src/index.ts, yarn.lock
Just bumping deps + outdated `snaps-*` deps to solve the `elliptic` audit error.
```console
├─ browserify-sign@npm:4.2.3
│  └─ elliptic@npm:6.6.1 (via npm:^6.5.5)
│
└─ create-ecdh@npm:4.0.4
└─ elliptic@npm:6.6.1 (via npm:^6.5.3)
```
=> chore: bump `crypto-browserify@^3.12.1` + `snaps-*`
